### ISSUE TITLE
Detail view open after changing filters

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#101]
> if you have a detail view open, then switch to one of the filters, the sidebar stays open when it used to close, so you get where the left detail view doesn’t match what’s shown in the right.

**Comment by dmsnell** [comment]
Sounds like we need to dispatch some kind of `CLOSE_DRAWER` when we see the `SELECT_FILTER` action

**Comment by drw158** [comment]
Is there any way to know how/if we did it before? I think I remember the drawer closing before the iframe removal.

**Comment by dmsnell** [comment]
@drw158 it appears like the old behavior was a consequence of notes disappearing from the filtered list when switching filters. it didn't intrinsically define the behavior. to verify:

 - load a front-end site (still has the iframe) such as MC or en.blog.wordpress.com
 - open the notes panel
 - open a comment note
 - switch to comment view (drawer still open)
 - switch to liker view (drawer closes because comment note no longer visible)

**Comment by drw158** [comment]
Ok, I seem to remember it always closing when you click on another filter, but maybe I'm remembering incorrectly.

Seems like we need to create a new behavior to always close the detail view when changing filters.

**Comment by drw158** [comment]
I just tested the panel in MC, and it acts differently than the panel on the front end. MC matches the behavior that existed before the iframe removal. 

If you go to MC, click on a note, then click on another filter. The detail view closes.
