### ISSUE TITLE
Giant Emojis

### ISSUE THREAD

**Issue by justinshreve** [Automattic/notifications-panel#275]
This is probably one of the funniest bugs I've come across, but I have a post where the emojis are coming through massive in the notifications panel.

<img width="411" alt="screen shot 2018-05-25 at 12 16 40 pm" src="https://user-images.githubusercontent.com/689165/40554988-8ace1668-6015-11e8-97b6-db0fab01c2d3.png">

The post in question is p90Yrv-GY-p2.

**Comment by dmsnell** [comment]
this is probably because these images are SVGs without inherent size values.

in #196 I added a CSS rule to [set the `max-width` to 100%](https://github.com/Automattic/notifications-panel/pull/196/files#diff-f4ca3f6f0bd9d140068adb06cc78c07eR510) and without an inherent width it looks like the browser is scaling SVGs all the way.

not sure what the fix is as we don't know how big these should be. maybe we need to hit this from the server and try to parse SVG attributes if we want to get it right - or make some dumb rule like "SVGs are small" and limit them to a max width in pixels… neither solution is good.

**Comment by dmsnell** [comment]
I take it back - in the post in question we had an `emoji` class on the image tag…maybe we can fix this easier and "well enough"

**Comment by kwight** [comment]
I think the "bug" is that @justinshreve doesn't ❤️ emojis enough.

**Comment by dmsnell** [comment]
Should have been resolved in r176030-wpcpm - @justinshreve would you mind looking at that notification again to confirm?

**Comment by justinshreve** [comment]
Confirmed the issue is resolved! Thank you!
